version: 2

general:
  artifacts:
    - coverage/

defaults: &defaults
  working_directory: ~/Ignite
  docker:
    - image: circleci/node:9.5.0
    
jobs:
  build:
    <<: *defaults
    steps:
      - run: mkdir ~/.ssh && ssh-keyscan -t rsa github.intuit.com >> ~/.ssh/known_hosts
      - checkout
      - restore_cache:
          keys: 
            # # Find a cache corresponding to this specific package.json checksum
            # # when this file is changed, this key will fail
            - ignite-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
            - ignite-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - ignite-{{ .Branch }}
            # # Find the most recent cache used from any branch
            - ignite-master
            - ignite-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: ignite-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
              - .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/Ignite   
      - run:
          name: Lint
          command: yarn lint
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/Ignite 
      - run:
          name: Test
          command: yarn test --ci
          environment:
            JEST_JUNIT_OUTPUT: "coverage/junitjunit.xml"
      - store_test_results:
          path: coverage/junit
      - store_artifacts:
          path: coverage/junit
      - run:
          name: Send CodeCov Results
          command: bash <(curl -s https://codecov.tools.a.intuit.com/bash) -t $CODECOV_KEY
  publishLibrary:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/Ignite 
      - run:
          name: Build Library
          command: yarn build:lib
      - run:
          name: Publish Library
          command: scripts/ci-publish.sh
      - persist_to_workspace:
          root: .
          paths:
              - dist/
  publishDocs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/Ignite 
      - run:
          name: Build Library
          command: yarn build:lib
      - run:
          name: Publish Docs
          command: yarn publish:docs
  pr-check:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/Ignite
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: PR Check
          command: scripts/pr-check.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - pr-check:
          requires:
              - build
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
              - build
          filters:
            tags:
              only: /.*/
      - test:
          requires:
              - build
          filters:
            tags:
              only: /.*/
      - publishLibrary:
          requires:
              - lint
              - test
          filters:
            branches:
              only:
                - master
      - publishDocs:
          requires:
              - publishLibrary
          filters:
            branches:
              only:
                - master
